@startuml mid-western-house-implementation

interface WaterSource {
   + getWater()
}

interface FoodSource {
   + getFood()
}

interface EnergySource {
   + getEnergy()
}

interface House extends WaterSource, FoodSource, EnergySource {
   + getWater()
   + getFood()
   + getEnergy()
}

class MidWesternHouse implements House {
   - WaterSource[] waterSources
   - FoodSource[] foodSources
   - EnergySource[] energySources
   
   + getWater()
   + getFood()
   + getEnergy()
}

' Responsible for the collection, storage, and purification of rain-water
class RainWaterHarvester  << (M,#FF7700) >> implements WaterSource {
   + getWater()
}


class AquaponicGreenHouse << (M,#FF7700) >> implements FoodSource {
   + getFood()
}


class SolarPanelArray << (M,#FF7700) >> implements EnergySource {
   + getEnergy()
}

MidWesternHouse ..> RainWaterHarvester
MidWesternHouse ..-> AquaponicGreenHouse
MidWesternHouse ..> SolarPanelArray
@enduml
