@startuml mid-western-house-implementation
interface House {
   getWater()
   getFood()
   getEnergy()
}

class MidWesternHouse implements House {
   getWater()
   getFood()
   getEnergy()
}

' Responsible for the collection, storage, and purification of rain-water
class RainWaterHarvester << (M,#FF7700) >> {
   getWater()
}


class AquaponicGreenHouse << (M,#FF7700) >> {
   getFood()
}


class SolarPanelArray << (M,#FF7700) >> {
   getEnergy()
}

MidWesternHouse ..> RainWaterHarvester
MidWesternHouse ..-> AquaponicGreenHouse
MidWesternHouse ..> SolarPanelArray
@enduml
